# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='bitcoin.proto',
  package='bitcoinformat',
  serialized_pb='\n\rbitcoin.proto\x12\rbitcoinformat\"\x1b\n\x0bTransaction\x12\x0c\n\x04hash\x18\x01 \x02(\t\"\x87\x02\n\x05\x42lock\x12\x0c\n\x04hash\x18\x01 \x02(\t\x12\x15\n\rconfirmations\x18\x02 \x02(\x05\x12\x0c\n\x04size\x18\x03 \x02(\x05\x12\x0e\n\x06height\x18\x04 \x02(\x05\x12&\n\x02tx\x18\x05 \x03(\x0b\x32\x1a.bitcoinformat.Transaction\x12\x0f\n\x07version\x18\x06 \x02(\x05\x12\x0c\n\x04time\x18\x07 \x02(\x05\x12\r\n\x05nonce\x18\x08 \x02(\x01\x12\x0c\n\x04\x62its\x18\t \x02(\t\x12\x12\n\ndifficulty\x18\n \x02(\x02\x12\x11\n\tchainwork\x18\x0b \x02(\t\x12\x19\n\x11previousblockhash\x18\x0c \x02(\t\x12\x15\n\rnextblockhash\x18\r \x02(\t\"Y\n\x08RecordIn\x12\x0c\n\x04txid\x18\x01 \x01(\t\x12\x0c\n\x04vout\x18\x02 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x02(\t\x12\x0e\n\x06\x61mount\x18\x04 \x02(\x01\x12\x10\n\x08sequence\x18\x05 \x02(\x05\"7\n\tRecordOut\x12\t\n\x01n\x18\x01 \x02(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x02(\t\x12\x0e\n\x06\x61mount\x18\x03 \x02(\x01\"\xdd\x01\n\x0fTransactionFull\x12\x0c\n\x04txid\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\x05\x12\x10\n\x08locktime\x18\x03 \x02(\x05\x12$\n\x03vin\x18\x04 \x03(\x0b\x32\x17.bitcoinformat.RecordIn\x12&\n\x04vout\x18\x05 \x03(\x0b\x32\x18.bitcoinformat.RecordOut\x12\x11\n\tblockhash\x18\x06 \x02(\t\x12\x15\n\rconfirmations\x18\x07 \x02(\x05\x12\x0e\n\x06txtime\x18\x08 \x02(\x05\x12\x11\n\tblocktime\x18\t \x02(\x05')




_TRANSACTION = descriptor.Descriptor(
  name='Transaction',
  full_name='bitcoinformat.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hash', full_name='bitcoinformat.Transaction.hash', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=59,
)


_BLOCK = descriptor.Descriptor(
  name='Block',
  full_name='bitcoinformat.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hash', full_name='bitcoinformat.Block.hash', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='confirmations', full_name='bitcoinformat.Block.confirmations', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size', full_name='bitcoinformat.Block.size', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='height', full_name='bitcoinformat.Block.height', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tx', full_name='bitcoinformat.Block.tx', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='bitcoinformat.Block.version', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time', full_name='bitcoinformat.Block.time', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nonce', full_name='bitcoinformat.Block.nonce', index=7,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bits', full_name='bitcoinformat.Block.bits', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='difficulty', full_name='bitcoinformat.Block.difficulty', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chainwork', full_name='bitcoinformat.Block.chainwork', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='previousblockhash', full_name='bitcoinformat.Block.previousblockhash', index=11,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nextblockhash', full_name='bitcoinformat.Block.nextblockhash', index=12,
      number=13, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=62,
  serialized_end=325,
)


_RECORDIN = descriptor.Descriptor(
  name='RecordIn',
  full_name='bitcoinformat.RecordIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='txid', full_name='bitcoinformat.RecordIn.txid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vout', full_name='bitcoinformat.RecordIn.vout', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='bitcoinformat.RecordIn.address', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amount', full_name='bitcoinformat.RecordIn.amount', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sequence', full_name='bitcoinformat.RecordIn.sequence', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=327,
  serialized_end=416,
)


_RECORDOUT = descriptor.Descriptor(
  name='RecordOut',
  full_name='bitcoinformat.RecordOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='n', full_name='bitcoinformat.RecordOut.n', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='bitcoinformat.RecordOut.address', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amount', full_name='bitcoinformat.RecordOut.amount', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=418,
  serialized_end=473,
)


_TRANSACTIONFULL = descriptor.Descriptor(
  name='TransactionFull',
  full_name='bitcoinformat.TransactionFull',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='txid', full_name='bitcoinformat.TransactionFull.txid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='bitcoinformat.TransactionFull.version', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='locktime', full_name='bitcoinformat.TransactionFull.locktime', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vin', full_name='bitcoinformat.TransactionFull.vin', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vout', full_name='bitcoinformat.TransactionFull.vout', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blockhash', full_name='bitcoinformat.TransactionFull.blockhash', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='confirmations', full_name='bitcoinformat.TransactionFull.confirmations', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='txtime', full_name='bitcoinformat.TransactionFull.txtime', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blocktime', full_name='bitcoinformat.TransactionFull.blocktime', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=476,
  serialized_end=697,
)

_BLOCK.fields_by_name['tx'].message_type = _TRANSACTION
_TRANSACTIONFULL.fields_by_name['vin'].message_type = _RECORDIN
_TRANSACTIONFULL.fields_by_name['vout'].message_type = _RECORDOUT
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['RecordIn'] = _RECORDIN
DESCRIPTOR.message_types_by_name['RecordOut'] = _RECORDOUT
DESCRIPTOR.message_types_by_name['TransactionFull'] = _TRANSACTIONFULL

class Transaction(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRANSACTION
  
  # @@protoc_insertion_point(class_scope:bitcoinformat.Transaction)

class Block(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLOCK
  
  # @@protoc_insertion_point(class_scope:bitcoinformat.Block)

class RecordIn(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RECORDIN
  
  # @@protoc_insertion_point(class_scope:bitcoinformat.RecordIn)

class RecordOut(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RECORDOUT
  
  # @@protoc_insertion_point(class_scope:bitcoinformat.RecordOut)

class TransactionFull(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRANSACTIONFULL
  
  # @@protoc_insertion_point(class_scope:bitcoinformat.TransactionFull)

# @@protoc_insertion_point(module_scope)
