// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/bitcoin.proto

package hi.mr.proto;

public final class Bitcoin {
  private Bitcoin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TransactionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string hash = 1;
    boolean hasHash();
    String getHash();
  }
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessage
      implements TransactionOrBuilder {
    // Use Transaction.newBuilder() to construct.
    private Transaction(Builder builder) {
      super(builder);
    }
    private Transaction(boolean noInit) {}
    
    private static final Transaction defaultInstance;
    public static Transaction getDefaultInstance() {
      return defaultInstance;
    }
    
    public Transaction getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hi.mr.proto.Bitcoin.internal_static_hi_mr_proto_Transaction_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hi.mr.proto.Bitcoin.internal_static_hi_mr_proto_Transaction_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string hash = 1;
    public static final int HASH_FIELD_NUMBER = 1;
    private java.lang.Object hash_;
    public boolean hasHash() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getHash() {
      java.lang.Object ref = hash_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          hash_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      hash_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHashBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHashBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static hi.mr.proto.Bitcoin.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static hi.mr.proto.Bitcoin.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static hi.mr.proto.Bitcoin.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hi.mr.proto.Bitcoin.Transaction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements hi.mr.proto.Bitcoin.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hi.mr.proto.Bitcoin.internal_static_hi_mr_proto_Transaction_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hi.mr.proto.Bitcoin.internal_static_hi_mr_proto_Transaction_fieldAccessorTable;
      }
      
      // Construct using hi.mr.proto.Bitcoin.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        hash_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hi.mr.proto.Bitcoin.Transaction.getDescriptor();
      }
      
      public hi.mr.proto.Bitcoin.Transaction getDefaultInstanceForType() {
        return hi.mr.proto.Bitcoin.Transaction.getDefaultInstance();
      }
      
      public hi.mr.proto.Bitcoin.Transaction build() {
        hi.mr.proto.Bitcoin.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private hi.mr.proto.Bitcoin.Transaction buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        hi.mr.proto.Bitcoin.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public hi.mr.proto.Bitcoin.Transaction buildPartial() {
        hi.mr.proto.Bitcoin.Transaction result = new hi.mr.proto.Bitcoin.Transaction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hash_ = hash_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hi.mr.proto.Bitcoin.Transaction) {
          return mergeFrom((hi.mr.proto.Bitcoin.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(hi.mr.proto.Bitcoin.Transaction other) {
        if (other == hi.mr.proto.Bitcoin.Transaction.getDefaultInstance()) return this;
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHash()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              hash_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string hash = 1;
      private java.lang.Object hash_ = "";
      public boolean hasHash() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getHash() {
        java.lang.Object ref = hash_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          hash_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHash(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hash_ = value;
        onChanged();
        return this;
      }
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      void setHash(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        hash_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:hi.mr.proto.Transaction)
    }
    
    static {
      defaultInstance = new Transaction(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hi.mr.proto.Transaction)
  }
  
  public interface BlockOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string hash = 1;
    boolean hasHash();
    String getHash();
    
    // required int32 confirmations = 2;
    boolean hasConfirmations();
    int getConfirmations();
    
    // required int32 size = 3;
    boolean hasSize();
    int getSize();
    
    // required int32 height = 4;
    boolean hasHeight();
    int getHeight();
    
    // repeated .hi.mr.proto.Transaction tx = 5;
    java.util.List<hi.mr.proto.Bitcoin.Transaction> 
        getTxList();
    hi.mr.proto.Bitcoin.Transaction getTx(int index);
    int getTxCount();
    java.util.List<? extends hi.mr.proto.Bitcoin.TransactionOrBuilder> 
        getTxOrBuilderList();
    hi.mr.proto.Bitcoin.TransactionOrBuilder getTxOrBuilder(
        int index);
    
    // required int32 version = 6;
    boolean hasVersion();
    int getVersion();
    
    // required int32 time = 7;
    boolean hasTime();
    int getTime();
    
    // required double nonce = 8;
    boolean hasNonce();
    double getNonce();
    
    // required string bits = 9;
    boolean hasBits();
    String getBits();
    
    // required float difficulty = 10;
    boolean hasDifficulty();
    float getDifficulty();
    
    // required string chainwork = 11;
    boolean hasChainwork();
    String getChainwork();
    
    // required string previousblockhash = 12;
    boolean hasPreviousblockhash();
    String getPreviousblockhash();
    
    // required string nextblockhash = 13;
    boolean hasNextblockhash();
    String getNextblockhash();
  }
  public static final class Block extends
      com.google.protobuf.GeneratedMessage
      implements BlockOrBuilder {
    // Use Block.newBuilder() to construct.
    private Block(Builder builder) {
      super(builder);
    }
    private Block(boolean noInit) {}
    
    private static final Block defaultInstance;
    public static Block getDefaultInstance() {
      return defaultInstance;
    }
    
    public Block getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hi.mr.proto.Bitcoin.internal_static_hi_mr_proto_Block_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hi.mr.proto.Bitcoin.internal_static_hi_mr_proto_Block_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string hash = 1;
    public static final int HASH_FIELD_NUMBER = 1;
    private java.lang.Object hash_;
    public boolean hasHash() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getHash() {
      java.lang.Object ref = hash_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          hash_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 confirmations = 2;
    public static final int CONFIRMATIONS_FIELD_NUMBER = 2;
    private int confirmations_;
    public boolean hasConfirmations() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getConfirmations() {
      return confirmations_;
    }
    
    // required int32 size = 3;
    public static final int SIZE_FIELD_NUMBER = 3;
    private int size_;
    public boolean hasSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getSize() {
      return size_;
    }
    
    // required int32 height = 4;
    public static final int HEIGHT_FIELD_NUMBER = 4;
    private int height_;
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getHeight() {
      return height_;
    }
    
    // repeated .hi.mr.proto.Transaction tx = 5;
    public static final int TX_FIELD_NUMBER = 5;
    private java.util.List<hi.mr.proto.Bitcoin.Transaction> tx_;
    public java.util.List<hi.mr.proto.Bitcoin.Transaction> getTxList() {
      return tx_;
    }
    public java.util.List<? extends hi.mr.proto.Bitcoin.TransactionOrBuilder> 
        getTxOrBuilderList() {
      return tx_;
    }
    public int getTxCount() {
      return tx_.size();
    }
    public hi.mr.proto.Bitcoin.Transaction getTx(int index) {
      return tx_.get(index);
    }
    public hi.mr.proto.Bitcoin.TransactionOrBuilder getTxOrBuilder(
        int index) {
      return tx_.get(index);
    }
    
    // required int32 version = 6;
    public static final int VERSION_FIELD_NUMBER = 6;
    private int version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getVersion() {
      return version_;
    }
    
    // required int32 time = 7;
    public static final int TIME_FIELD_NUMBER = 7;
    private int time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getTime() {
      return time_;
    }
    
    // required double nonce = 8;
    public static final int NONCE_FIELD_NUMBER = 8;
    private double nonce_;
    public boolean hasNonce() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public double getNonce() {
      return nonce_;
    }
    
    // required string bits = 9;
    public static final int BITS_FIELD_NUMBER = 9;
    private java.lang.Object bits_;
    public boolean hasBits() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getBits() {
      java.lang.Object ref = bits_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          bits_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBitsBytes() {
      java.lang.Object ref = bits_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        bits_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required float difficulty = 10;
    public static final int DIFFICULTY_FIELD_NUMBER = 10;
    private float difficulty_;
    public boolean hasDifficulty() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public float getDifficulty() {
      return difficulty_;
    }
    
    // required string chainwork = 11;
    public static final int CHAINWORK_FIELD_NUMBER = 11;
    private java.lang.Object chainwork_;
    public boolean hasChainwork() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getChainwork() {
      java.lang.Object ref = chainwork_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          chainwork_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getChainworkBytes() {
      java.lang.Object ref = chainwork_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        chainwork_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string previousblockhash = 12;
    public static final int PREVIOUSBLOCKHASH_FIELD_NUMBER = 12;
    private java.lang.Object previousblockhash_;
    public boolean hasPreviousblockhash() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public String getPreviousblockhash() {
      java.lang.Object ref = previousblockhash_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          previousblockhash_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPreviousblockhashBytes() {
      java.lang.Object ref = previousblockhash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        previousblockhash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string nextblockhash = 13;
    public static final int NEXTBLOCKHASH_FIELD_NUMBER = 13;
    private java.lang.Object nextblockhash_;
    public boolean hasNextblockhash() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getNextblockhash() {
      java.lang.Object ref = nextblockhash_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nextblockhash_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNextblockhashBytes() {
      java.lang.Object ref = nextblockhash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nextblockhash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      hash_ = "";
      confirmations_ = 0;
      size_ = 0;
      height_ = 0;
      tx_ = java.util.Collections.emptyList();
      version_ = 0;
      time_ = 0;
      nonce_ = 0D;
      bits_ = "";
      difficulty_ = 0F;
      chainwork_ = "";
      previousblockhash_ = "";
      nextblockhash_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConfirmations()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNonce()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBits()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDifficulty()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChainwork()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPreviousblockhash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNextblockhash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTxCount(); i++) {
        if (!getTx(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHashBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, confirmations_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, size_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, height_);
      }
      for (int i = 0; i < tx_.size(); i++) {
        output.writeMessage(5, tx_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, version_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, time_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(8, nonce_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(9, getBitsBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeFloat(10, difficulty_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(11, getChainworkBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(12, getPreviousblockhashBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(13, getNextblockhashBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHashBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, confirmations_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, size_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, height_);
      }
      for (int i = 0; i < tx_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, tx_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, version_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, time_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, nonce_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getBitsBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, difficulty_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getChainworkBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getPreviousblockhashBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getNextblockhashBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static hi.mr.proto.Bitcoin.Block parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Block parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Block parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Block parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Block parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Block parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Block parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static hi.mr.proto.Bitcoin.Block parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static hi.mr.proto.Bitcoin.Block parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static hi.mr.proto.Bitcoin.Block parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hi.mr.proto.Bitcoin.Block prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements hi.mr.proto.Bitcoin.BlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hi.mr.proto.Bitcoin.internal_static_hi_mr_proto_Block_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hi.mr.proto.Bitcoin.internal_static_hi_mr_proto_Block_fieldAccessorTable;
      }
      
      // Construct using hi.mr.proto.Bitcoin.Block.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTxFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        hash_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        confirmations_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (txBuilder_ == null) {
          tx_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          txBuilder_.clear();
        }
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        nonce_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        bits_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        difficulty_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000200);
        chainwork_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        previousblockhash_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        nextblockhash_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hi.mr.proto.Bitcoin.Block.getDescriptor();
      }
      
      public hi.mr.proto.Bitcoin.Block getDefaultInstanceForType() {
        return hi.mr.proto.Bitcoin.Block.getDefaultInstance();
      }
      
      public hi.mr.proto.Bitcoin.Block build() {
        hi.mr.proto.Bitcoin.Block result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private hi.mr.proto.Bitcoin.Block buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        hi.mr.proto.Bitcoin.Block result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public hi.mr.proto.Bitcoin.Block buildPartial() {
        hi.mr.proto.Bitcoin.Block result = new hi.mr.proto.Bitcoin.Block(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hash_ = hash_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.confirmations_ = confirmations_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.height_ = height_;
        if (txBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            tx_ = java.util.Collections.unmodifiableList(tx_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.tx_ = tx_;
        } else {
          result.tx_ = txBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.nonce_ = nonce_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.bits_ = bits_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.difficulty_ = difficulty_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.chainwork_ = chainwork_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.previousblockhash_ = previousblockhash_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.nextblockhash_ = nextblockhash_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hi.mr.proto.Bitcoin.Block) {
          return mergeFrom((hi.mr.proto.Bitcoin.Block)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(hi.mr.proto.Bitcoin.Block other) {
        if (other == hi.mr.proto.Bitcoin.Block.getDefaultInstance()) return this;
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        if (other.hasConfirmations()) {
          setConfirmations(other.getConfirmations());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (txBuilder_ == null) {
          if (!other.tx_.isEmpty()) {
            if (tx_.isEmpty()) {
              tx_ = other.tx_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureTxIsMutable();
              tx_.addAll(other.tx_);
            }
            onChanged();
          }
        } else {
          if (!other.tx_.isEmpty()) {
            if (txBuilder_.isEmpty()) {
              txBuilder_.dispose();
              txBuilder_ = null;
              tx_ = other.tx_;
              bitField0_ = (bitField0_ & ~0x00000010);
              txBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTxFieldBuilder() : null;
            } else {
              txBuilder_.addAllMessages(other.tx_);
            }
          }
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasNonce()) {
          setNonce(other.getNonce());
        }
        if (other.hasBits()) {
          setBits(other.getBits());
        }
        if (other.hasDifficulty()) {
          setDifficulty(other.getDifficulty());
        }
        if (other.hasChainwork()) {
          setChainwork(other.getChainwork());
        }
        if (other.hasPreviousblockhash()) {
          setPreviousblockhash(other.getPreviousblockhash());
        }
        if (other.hasNextblockhash()) {
          setNextblockhash(other.getNextblockhash());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHash()) {
          
          return false;
        }
        if (!hasConfirmations()) {
          
          return false;
        }
        if (!hasSize()) {
          
          return false;
        }
        if (!hasHeight()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasNonce()) {
          
          return false;
        }
        if (!hasBits()) {
          
          return false;
        }
        if (!hasDifficulty()) {
          
          return false;
        }
        if (!hasChainwork()) {
          
          return false;
        }
        if (!hasPreviousblockhash()) {
          
          return false;
        }
        if (!hasNextblockhash()) {
          
          return false;
        }
        for (int i = 0; i < getTxCount(); i++) {
          if (!getTx(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              hash_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              confirmations_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              size_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              height_ = input.readInt32();
              break;
            }
            case 42: {
              hi.mr.proto.Bitcoin.Transaction.Builder subBuilder = hi.mr.proto.Bitcoin.Transaction.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTx(subBuilder.buildPartial());
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              version_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              time_ = input.readInt32();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              nonce_ = input.readDouble();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              bits_ = input.readBytes();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000200;
              difficulty_ = input.readFloat();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              chainwork_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              previousblockhash_ = input.readBytes();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              nextblockhash_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string hash = 1;
      private java.lang.Object hash_ = "";
      public boolean hasHash() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getHash() {
        java.lang.Object ref = hash_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          hash_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHash(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hash_ = value;
        onChanged();
        return this;
      }
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      void setHash(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        hash_ = value;
        onChanged();
      }
      
      // required int32 confirmations = 2;
      private int confirmations_ ;
      public boolean hasConfirmations() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getConfirmations() {
        return confirmations_;
      }
      public Builder setConfirmations(int value) {
        bitField0_ |= 0x00000002;
        confirmations_ = value;
        onChanged();
        return this;
      }
      public Builder clearConfirmations() {
        bitField0_ = (bitField0_ & ~0x00000002);
        confirmations_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 size = 3;
      private int size_ ;
      public boolean hasSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getSize() {
        return size_;
      }
      public Builder setSize(int value) {
        bitField0_ |= 0x00000004;
        size_ = value;
        onChanged();
        return this;
      }
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        size_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 height = 4;
      private int height_ ;
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getHeight() {
        return height_;
      }
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000008;
        height_ = value;
        onChanged();
        return this;
      }
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000008);
        height_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .hi.mr.proto.Transaction tx = 5;
      private java.util.List<hi.mr.proto.Bitcoin.Transaction> tx_ =
        java.util.Collections.emptyList();
      private void ensureTxIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          tx_ = new java.util.ArrayList<hi.mr.proto.Bitcoin.Transaction>(tx_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          hi.mr.proto.Bitcoin.Transaction, hi.mr.proto.Bitcoin.Transaction.Builder, hi.mr.proto.Bitcoin.TransactionOrBuilder> txBuilder_;
      
      public java.util.List<hi.mr.proto.Bitcoin.Transaction> getTxList() {
        if (txBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tx_);
        } else {
          return txBuilder_.getMessageList();
        }
      }
      public int getTxCount() {
        if (txBuilder_ == null) {
          return tx_.size();
        } else {
          return txBuilder_.getCount();
        }
      }
      public hi.mr.proto.Bitcoin.Transaction getTx(int index) {
        if (txBuilder_ == null) {
          return tx_.get(index);
        } else {
          return txBuilder_.getMessage(index);
        }
      }
      public Builder setTx(
          int index, hi.mr.proto.Bitcoin.Transaction value) {
        if (txBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTxIsMutable();
          tx_.set(index, value);
          onChanged();
        } else {
          txBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTx(
          int index, hi.mr.proto.Bitcoin.Transaction.Builder builderForValue) {
        if (txBuilder_ == null) {
          ensureTxIsMutable();
          tx_.set(index, builderForValue.build());
          onChanged();
        } else {
          txBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTx(hi.mr.proto.Bitcoin.Transaction value) {
        if (txBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTxIsMutable();
          tx_.add(value);
          onChanged();
        } else {
          txBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTx(
          int index, hi.mr.proto.Bitcoin.Transaction value) {
        if (txBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTxIsMutable();
          tx_.add(index, value);
          onChanged();
        } else {
          txBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTx(
          hi.mr.proto.Bitcoin.Transaction.Builder builderForValue) {
        if (txBuilder_ == null) {
          ensureTxIsMutable();
          tx_.add(builderForValue.build());
          onChanged();
        } else {
          txBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTx(
          int index, hi.mr.proto.Bitcoin.Transaction.Builder builderForValue) {
        if (txBuilder_ == null) {
          ensureTxIsMutable();
          tx_.add(index, builderForValue.build());
          onChanged();
        } else {
          txBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTx(
          java.lang.Iterable<? extends hi.mr.proto.Bitcoin.Transaction> values) {
        if (txBuilder_ == null) {
          ensureTxIsMutable();
          super.addAll(values, tx_);
          onChanged();
        } else {
          txBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTx() {
        if (txBuilder_ == null) {
          tx_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          txBuilder_.clear();
        }
        return this;
      }
      public Builder removeTx(int index) {
        if (txBuilder_ == null) {
          ensureTxIsMutable();
          tx_.remove(index);
          onChanged();
        } else {
          txBuilder_.remove(index);
        }
        return this;
      }
      public hi.mr.proto.Bitcoin.Transaction.Builder getTxBuilder(
          int index) {
        return getTxFieldBuilder().getBuilder(index);
      }
      public hi.mr.proto.Bitcoin.TransactionOrBuilder getTxOrBuilder(
          int index) {
        if (txBuilder_ == null) {
          return tx_.get(index);  } else {
          return txBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends hi.mr.proto.Bitcoin.TransactionOrBuilder> 
           getTxOrBuilderList() {
        if (txBuilder_ != null) {
          return txBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tx_);
        }
      }
      public hi.mr.proto.Bitcoin.Transaction.Builder addTxBuilder() {
        return getTxFieldBuilder().addBuilder(
            hi.mr.proto.Bitcoin.Transaction.getDefaultInstance());
      }
      public hi.mr.proto.Bitcoin.Transaction.Builder addTxBuilder(
          int index) {
        return getTxFieldBuilder().addBuilder(
            index, hi.mr.proto.Bitcoin.Transaction.getDefaultInstance());
      }
      public java.util.List<hi.mr.proto.Bitcoin.Transaction.Builder> 
           getTxBuilderList() {
        return getTxFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          hi.mr.proto.Bitcoin.Transaction, hi.mr.proto.Bitcoin.Transaction.Builder, hi.mr.proto.Bitcoin.TransactionOrBuilder> 
          getTxFieldBuilder() {
        if (txBuilder_ == null) {
          txBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              hi.mr.proto.Bitcoin.Transaction, hi.mr.proto.Bitcoin.Transaction.Builder, hi.mr.proto.Bitcoin.TransactionOrBuilder>(
                  tx_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          tx_ = null;
        }
        return txBuilder_;
      }
      
      // required int32 version = 6;
      private int version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getVersion() {
        return version_;
      }
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000020;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000020);
        version_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 time = 7;
      private int time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getTime() {
        return time_;
      }
      public Builder setTime(int value) {
        bitField0_ |= 0x00000040;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        time_ = 0;
        onChanged();
        return this;
      }
      
      // required double nonce = 8;
      private double nonce_ ;
      public boolean hasNonce() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public double getNonce() {
        return nonce_;
      }
      public Builder setNonce(double value) {
        bitField0_ |= 0x00000080;
        nonce_ = value;
        onChanged();
        return this;
      }
      public Builder clearNonce() {
        bitField0_ = (bitField0_ & ~0x00000080);
        nonce_ = 0D;
        onChanged();
        return this;
      }
      
      // required string bits = 9;
      private java.lang.Object bits_ = "";
      public boolean hasBits() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getBits() {
        java.lang.Object ref = bits_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          bits_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBits(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        bits_ = value;
        onChanged();
        return this;
      }
      public Builder clearBits() {
        bitField0_ = (bitField0_ & ~0x00000100);
        bits_ = getDefaultInstance().getBits();
        onChanged();
        return this;
      }
      void setBits(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        bits_ = value;
        onChanged();
      }
      
      // required float difficulty = 10;
      private float difficulty_ ;
      public boolean hasDifficulty() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public float getDifficulty() {
        return difficulty_;
      }
      public Builder setDifficulty(float value) {
        bitField0_ |= 0x00000200;
        difficulty_ = value;
        onChanged();
        return this;
      }
      public Builder clearDifficulty() {
        bitField0_ = (bitField0_ & ~0x00000200);
        difficulty_ = 0F;
        onChanged();
        return this;
      }
      
      // required string chainwork = 11;
      private java.lang.Object chainwork_ = "";
      public boolean hasChainwork() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getChainwork() {
        java.lang.Object ref = chainwork_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          chainwork_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setChainwork(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        chainwork_ = value;
        onChanged();
        return this;
      }
      public Builder clearChainwork() {
        bitField0_ = (bitField0_ & ~0x00000400);
        chainwork_ = getDefaultInstance().getChainwork();
        onChanged();
        return this;
      }
      void setChainwork(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        chainwork_ = value;
        onChanged();
      }
      
      // required string previousblockhash = 12;
      private java.lang.Object previousblockhash_ = "";
      public boolean hasPreviousblockhash() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getPreviousblockhash() {
        java.lang.Object ref = previousblockhash_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          previousblockhash_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPreviousblockhash(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        previousblockhash_ = value;
        onChanged();
        return this;
      }
      public Builder clearPreviousblockhash() {
        bitField0_ = (bitField0_ & ~0x00000800);
        previousblockhash_ = getDefaultInstance().getPreviousblockhash();
        onChanged();
        return this;
      }
      void setPreviousblockhash(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        previousblockhash_ = value;
        onChanged();
      }
      
      // required string nextblockhash = 13;
      private java.lang.Object nextblockhash_ = "";
      public boolean hasNextblockhash() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public String getNextblockhash() {
        java.lang.Object ref = nextblockhash_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nextblockhash_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNextblockhash(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        nextblockhash_ = value;
        onChanged();
        return this;
      }
      public Builder clearNextblockhash() {
        bitField0_ = (bitField0_ & ~0x00001000);
        nextblockhash_ = getDefaultInstance().getNextblockhash();
        onChanged();
        return this;
      }
      void setNextblockhash(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00001000;
        nextblockhash_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:hi.mr.proto.Block)
    }
    
    static {
      defaultInstance = new Block(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hi.mr.proto.Block)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hi_mr_proto_Transaction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hi_mr_proto_Transaction_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hi_mr_proto_Block_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hi_mr_proto_Block_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/protobuf/bitcoin.proto\022\013hi.mr" +
      ".proto\"\033\n\013Transaction\022\014\n\004hash\030\001 \002(\t\"\205\002\n\005" +
      "Block\022\014\n\004hash\030\001 \002(\t\022\025\n\rconfirmations\030\002 \002" +
      "(\005\022\014\n\004size\030\003 \002(\005\022\016\n\006height\030\004 \002(\005\022$\n\002tx\030\005" +
      " \003(\0132\030.hi.mr.proto.Transaction\022\017\n\007versio" +
      "n\030\006 \002(\005\022\014\n\004time\030\007 \002(\005\022\r\n\005nonce\030\010 \002(\001\022\014\n\004" +
      "bits\030\t \002(\t\022\022\n\ndifficulty\030\n \002(\002\022\021\n\tchainw" +
      "ork\030\013 \002(\t\022\031\n\021previousblockhash\030\014 \002(\t\022\025\n\r" +
      "nextblockhash\030\r \002(\tB\tB\007Bitcoin"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hi_mr_proto_Transaction_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hi_mr_proto_Transaction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hi_mr_proto_Transaction_descriptor,
              new java.lang.String[] { "Hash", },
              hi.mr.proto.Bitcoin.Transaction.class,
              hi.mr.proto.Bitcoin.Transaction.Builder.class);
          internal_static_hi_mr_proto_Block_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_hi_mr_proto_Block_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hi_mr_proto_Block_descriptor,
              new java.lang.String[] { "Hash", "Confirmations", "Size", "Height", "Tx", "Version", "Time", "Nonce", "Bits", "Difficulty", "Chainwork", "Previousblockhash", "Nextblockhash", },
              hi.mr.proto.Bitcoin.Block.class,
              hi.mr.proto.Bitcoin.Block.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
